# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: czp123..
            # 从库数据源
            slave:
                # 从数据源默认关闭，如需开启请补充连接信息
                enabled: false
                url:
                username:
                password:
            # 连接池初始连接数
            initialSize: 5
            # 连接池最小空闲连接数
            minIdle: 10
            # 连接池最大活动连接数
            maxActive: 20
            # 获取连接等待超时时间（毫秒）
            maxWait: 60000
            # 建立连接超时时间（毫秒）
            connectTimeout: 30000
            # Socket 读超时时间（毫秒）
            socketTimeout: 60000
            # 间隔多久进行一次空闲连接检测（毫秒）
            timeBetweenEvictionRunsMillis: 60000
            # 连接在池中最小生存时间（毫秒）
            minEvictableIdleTimeMillis: 300000
            # 连接在池中最大生存时间（毫秒）
            maxEvictableIdleTimeMillis: 900000
            # 连接可用性校验 SQL
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 允许访问监控面板的地址白名单，留空表示不限制
                allow:
                url-pattern: /druid/*
                # Druid 监控页面账号密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 记录慢 SQL
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
